version: '2.4'

services:
  app:
    image: docker-app-data
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fooddb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 6969
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: fooddb
      MYSQL_ROOT_PASSWORD: 6969
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - /Users/nikhilwaghmode/Documents/test-food/food-app/food-app/db-init:/docker-entrypoint-initdb.d:rw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p6969"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  mysql_data:
